// Mocks generated by Mockito 5.4.5 from annotations
// in kicca/test/services/ai_suggestion_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:google_generative_ai/google_generative_ai.dart' as _i4;
import 'package:kicca/services/ai_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AIClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIClient extends _i1.Mock implements _i2.AIClient {
  MockAIClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.GenerateContentResponse> generateContent(String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#generateContent, [prompt]),
            returnValue: _i3.Future<_i4.GenerateContentResponse>.value(
              _i5.dummyValue<_i4.GenerateContentResponse>(
                this,
                Invocation.method(#generateContent, [prompt]),
              ),
            ),
          )
          as _i3.Future<_i4.GenerateContentResponse>);
}
